spring:
  config:
    import: application-kafka.yml
  profiles:
    group:
      local: kafka-local-window
      beta: kafka-beta-linux

  application:
    name: notiApiServer

  datasource:
    url: jdbc:mariadb://localhost:3306/x?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 300000
      pool-name: SpringBootJPAHikariCP

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
    open-in-view: false

logging:
  level:
    org.springframework.data.jpa.domain.support.AuditingEntityListener: DEBUG

server:
  port: 8081
