spring:
  config:
    activate:
      on-profile: kafka-local-window
  kafka:
    consumer:
      bootstrap-servers: 192.168.210.79:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: noti-local-group
      auto-offset-reset: earliest
      enable-auto-commit: false


---
spring:
  config:
    activate:
      on-profile: kafka-beta-linux

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: noti-beta-group
      auto-offset-reset: earliest
      enable-auto-commit: false

